### ISSUE TITLE
typing error in Vertex-Cover.ipynb

### ISSUE THREAD

**Issue by CreamyLong** [glassnotes/Intro-QC-TRIUMF#1]
the QUBO formula in the Intro-QC-TRIUMF/04-annealing-applications/Vertex-Cover.ipynb is wrong 
it should be  deg(Xv) not Xv

**Comment by glassnotes** [comment]
Hi @CreamyLong, you're absolutely right, good catch! :+1: I've pushed an update to the notebook and will resolve this issue.
